---
abstract: 'Create/open or unlink POSIX shared memory objects in Perl'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Devel::CheckLib: 0
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POSIX-RT-SharedMem
requires:
  Carp: 0
  Const::Fast: 0
  Exporter: 5.57
  Fcntl: 0
  File::Map: 0
  XSLoader: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=POSIX-RT-SharedMem
  repository: git://github.com/Leont/posix-rt-sharedmem.git
version: 0.07
