---
name: POSIX-RT-SharedMem
version: 0.03
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Create/open or unlink POSIX shared memory objects in Perl
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=POSIX::RT::SharedMem
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/posix-rt-sharedmem/tree
configure_requires:
  Module::Build: 0
requires:
  Exporter: 5.57
  File::Map: 0.19
  Readonly: 1.03
  perl: 5.008
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0
  Test::Exception: 0
  Test::More: 0
provides:
  POSIX::RT::SharedMem:
    file: lib/POSIX/RT/SharedMem.pm
    version: 0.03
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - mmap
  - memory mapping
  - shared memory
