---
abstract: 'Create/open or unlink POSIX shared memory objects in Perl'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::Exception: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  Devel::CheckLib: '0'
  Module::Build: '0.3601'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POSIX-RT-SharedMem
provides:
  POSIX::RT::SharedMem:
    file: lib/POSIX/RT/SharedMem.pm
    version: '0.09'
requires:
  Carp: '0'
  Exporter: '5.57'
  Fcntl: '0'
  File::Map: '0'
  XSLoader: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=POSIX-RT-SharedMem
  repository: git://github.com/Leont/posix-rt-sharedmem.git
version: '0.09'
